apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-app
  labels:
    app: mlops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mlops
  template:
    metadata:
      labels:
        app: mlops
    spec:
      containers:
        - name: mlops-container
          image: 905418476815.dkr.ecr.ap-south-1.amazonaws.com/mytest:latest
          ports:
            - containerPort: 80
